export const langs = [
    {
        label: 'Ingles',
        value: 'en'
    },
    {
        label: 'Español',
        value: 'es'
    },
    { "label": "Afrikaans", "value": "af" },
    { "label": "Basque", "value": "eu" },
    { "label": "Bulgarian", "value": "bg" },
    { "label": "Catalan", "value": "ca" },
    { "label": "Arabic (Egypt)", "value": "ar-EG" },
    { "label": "Arabic (Jordan)", "value": "ar-JO" },
    { "label": "Arabic (Kuwait)", "value": "ar-KW" },
    { "label": "Arabic (Lebanon)", "value": "ar-LB" },
    { "label": "Arabic (Qatar)", "value": "ar-QA" },
    { "label": "Arabic (UAE)", "value": "ar-AE" },
    { "label": "Arabic (Morocco)", "value": "ar-MA" },
    { "label": "Arabic (Iraq)", "value": "ar-IQ" },
    { "label": "Arabic (Algeria)", "value": "ar-DZ" },
    { "label": "Arabic (Bahrain)", "value": "ar-BH" },
    { "label": "Arabic (Lybia)", "value": "ar-LY" },
    { "label": "Arabic (Oman)", "value": "ar-OM" },
    { "label": "Arabic (Saudi Arabia)", "value": "ar-SA" },
    { "label": "Arabic (Tunisia)", "value": "ar-TN" },
    { "label": "Arabic (Yemen)", "value": "ar-YE" },
    { "label": "Czech", "value": "cs" },
    { "label": "Dutch", "value": "nl-NL" },
    { "label": "English (Australia)", "value": "en-AU" },
    { "label": "English (Canada)", "value": "en-CA" },
    { "label": "English (India)", "value": "en-IN" },
    { "label": "English (New Zealand)", "value": "en-NZ" },
    { "label": "English (South Africa)", "value": "en-ZA" },
    { "label": "English(UK)", "value": "en-GB" },
    { "label": "English(US)", "value": "en-US" },
    { "label": "Finnish", "value": "fi" },
    { "label": "French", "value": "fr-FR" },
    { "label": "Galician", "value": "gl" },
    { "label": "German", "value": "de-DE" },
    { "label": "Greek", "value": "el-GR" },
    { "label": "Hebrew", "value": "he" },
    { "label": "Hungarian", "value": "hu" },
    { "label": "Icelandic", "value": "is" },
    { "label": "Italian", "value": "it-IT" },
    { "label": "Indonesian", "value": "id" },
    { "label": "Japanese", "value": "ja" },
    { "label": "Korean", "value": "ko" },
    { "label": "Latin", "value": "la" },
    { "label": "Mandarin Chinese", "value": "zh-CN" },
    { "label": "Taiwanese", "value": "zh-TW" },
    { "label": "Cantonese", "value": "zh-HK" },
    { "label": "Malaysian", "value": "ms-MY" },
    { "label": "Norwegian", "value": "no-NO" },
    { "label": "Polish", "value": "pl" },
    { "label": "Pig Latin", "value": "xx-piglatin" },
    { "label": "Portuguese", "value": "pt-PT" },
    { "label": "Portuguese (Brasil)", "value": "pt-br" },
    { "label": "Romanian", "value": "ro-RO" },
    { "label": "Russian", "value": "ru" },
    { "label": "Serbian", "value": "sr-SP" },
    { "label": "Slovak", "value": "sk" },
    { "label": "Spanish (Argentina)", "value": "es-AR" },
    { "label": "Spanish (Bolivia)", "value": "es-BO" },
    { "label": "Spanish (Chile)", "value": "es-CL" },
    { "label": "Spanish (Colombia)", "value": "es-CO" },
    { "label": "Spanish (Costa Rica)", "value": "es-CR" },
    { "label": "Spanish (Dominican Republic)", "value": "es-DO" },
    { "label": "Spanish (Ecuador)", "value": "es-EC" },
    { "label": "Spanish (El Salvador)", "value": "es-SV" },
    { "label": "Spanish (Guatemala)", "value": "es-GT" },
    { "label": "Spanish (Honduras)", "value": "es-HN" },
    { "label": "Spanish (Mexico)", "value": "es-MX" },
    { "label": "Spanish (Nicaragua)", "value": "es-NI" },
    { "label": "Spanish (Panama)", "value": "es-PA" },
    { "label": "Spanish (Paraguay)", "value": "es-PY" },
    { "label": "Spanish (Peru)", "value": "es-PE" },
    { "label": "Spanish (Puerto Rico)", "value": "es-PR" },
    { "label": "Spanish (Spain)", "value": "es-ES" },
    { "label": "Spanish (US)", "value": "es-US" },
    { "label": "Spanish (Uruguay)", "value": "es-UY" },
    { "label": "Spanish (Venezuela)", "value": "es-VE" },
    { "label": "Swedish", "value": "sv-SE" },
    { "label": "Turkish", "value": "tr" },
    { "label": "Zulu", "value": "zu" }
]